environment:
  APP_AUTHOR: contact@bulldogandfisk.com
  MAIL_TO_ADDRESS: <your@email.here>
  MAIL_FROM_ADDRESS: ${ssm:mail.fromAddress}
  MAILGUN_API_KEY: ${ssm:mailgun.apiKey.${sls:stage}}
  MAILGUN_DOMAIN: ${ssm:mailgun.domain.${sls:stage}}
  SENDGRID_API_KEY: ${ssm:sendgrid.apiKey.${sls:stage}}
