---
openapi: 3.0.3
info:
  title: api-only
  description: Example of a pure REST API deployment
  version: 1.0.0
  contact:
    name: Bulldog and Fisk
    email: contact@bulldogandfisk.com
  license:
    name: AGPL-3.0-or-later
    url: https://spdx.org/licenses/AGPL-3.0-or-later.html
  termsOfService: https://spdx.org/licenses/AGPL-3.0-or-later.html
servers:
  - url: http://localhost:3000/dev
    description: Dev server
tags:
  - name: tagexample
    description: >
      You can set tags here in the root or per-path.
      If you do set path-level tags you need to define them here first.
      See https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#operation-object
paths:
  /zoom/events:
    post:
      x-actor-id: zoom/events
      description: >
        Catches ALL Zoom webhook events
      requestBody:
        description: >
          The Zoom event data
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Successfully received
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Invalid request
          content:
            text/plain:
              schema:
                type: string
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  responses:
    "200":
      description: General OK response
      content:
        text/html:
          schema:
            type: string
    "302":
      description: Found. Generally used for presigned urls.
      content:
        text/html:
          schema:
            type: string
    "303":
      description: See other. A type of redirect.
    "400":
      description: Bad request
      content:
        application/json:
          schema:
            type: object
    "401":
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
    "402":
      description: Payment required
      content:
        application/json:
          schema:
            type: object
    "403":
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
    "404":
      description: Not found
      content:
        application/json:
          schema:
            type: string
    "500":
      description: Internal server error
      content:
        application/json:
          schema:
            type: object

